description: This method retrieves information about all the DNS rules associated with a mobile edge application instance.
operationId: ApplicationsDnsRules.GET
produces:
- application/json
parameters:
- $ref: '#/parameters/Path.AppInstanceId'

responses:
  200:
    description: It is used to indicate nonspecific success. The response body contains a representation of the resource.
    schema:
      type: array
      items:
        type: object
        properties:
          DnsRule:
            $ref: '#/definitions/DnsRule'