parameters:
- $ref: '#/parameters/Path.AppInstanceId'
- $ref: '#/parameters/Path.SubscriptionType'
- $ref: '#/parameters/Path.SubscriptionId'

get:
  $ref: ./ApplicationsSubscription.GET.yaml

delete:
  $ref: ./ApplicationsSubscription.DELETE.yaml