description: This method retrieves information about a DNS rule associated with a mobile edge application instance. 
operationId: ApplicationsDnsRule.GET
produces:
- application/json

responses:
  200:
    description: It is used to indicate nonspecific success. The response body contains a representation of the resource.
    schema:
      type: object
      properties:
        DnsRule:
          $ref: '#/definitions/DnsRule'
    examples:
      application/json:
        $ref: '../examples/DnsRule.json' 