################################################################################
#                        Open API specification version                        #
################################################################################
swagger: '2.0'

################################################################################
#                              Document Information                            #
################################################################################
info:
  $ref: './info/index.yaml'

################################################################################
#                               External Documents                             #
################################################################################
externalDocs: 
  $ref: './externalDocs/index.yaml'

host: 127.0.0.1:8081
basePath: /exampleAPI/mp1/v1/
schemes:
- http
- https
consumes:
- application/json
produces:
- application/json

################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
  $ref: ./parameters/index.yaml

################################################################################
#                                   paths                                      #
################################################################################
paths:
  $ref: './paths/index.yaml'

################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  $ref: './definitions/index.yaml'